### ISSUE TITLE
MDSJ Java library not found

### ISSUE THREAD

**Issue by raffam** [statnet/ndtv#38]
I get this error message

```
Calculating layout for network slice from time  0 to 1
The MDSJ Java library does not appear to be installed. The ndtv package can use MDSJ to provide a fast accurate layout algorithm. It can be downloaded from http://algo.uni-konstanz.de/software/mdsj/
Do you want to automatically download and install the MDSJ Java library? (y/N): y
installing MDSJ to directory /home/raffaele/R/x86_64-pc-linux-gnu-library/3.5/ndtv/java/
trying URL 'http://algo.uni-konstanz.de/software/mdsj/mdsj.jar'
Error in download.file(url = mdsjURL, destfile = file.path(install.path,  : 
  cannot open URL 'http://algo.uni-konstanz.de/software/mdsj/mdsj.jar'
```

In effect, going to [here](https://www.algo.uni-konstanz.de/software/mdsj/) returns a 404 error. Is the library discontinued?

**Comment by skyebend** [comment]
oh no!  I will try to contact the author to find a new url for the package.  I do see it in the internet archive at https://web.archive.org/web/20180719063437/http://algo.uni-konstanz.de/software/mdsj/mdsj.jar

**Comment by skyebend** [comment]
created a temporary repository to host the jar on github https://github.com/skyebend/mdsj/blob/master/mdsj.jar

**Comment by raffam** [comment]
ok, I'll try it. thanks
