### ISSUE TITLE
Warning message from new CRAN check threating package removal

### ISSUE THREAD

**Issue by skyebend** [statnet/ndtv#43]
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_ndtv.html>.

Please correct before 2020-10-28 to safely retain your package on CRAN.

The CRAN Team

**Comment by krivit** [comment]
This should go away once the new `tergm` is on CRAN.

**Comment by krivit** [comment]
`tergm` 3.7 is on CRAN. Has the warning gone away?

**Comment by skyebend** [comment]
Yes! Fixed!
