### ISSUE TITLE
Change dynamic xlab graphical parameter

### ISSUE THREAD

**Issue by Dekermanjian** [statnet/ndtv#49]
I can not find any documentation to change the default function that is passed to the xlab parameter to my own customers function. Does this documentation exist somewhere? Any help would be appreciated.

**Comment by Dekermanjian** [comment]
I figured this out by looking at the source code. I think it would still be nice to have an example to document how others can achieve this.

**Comment by tedmoorman** [comment]
It appears to be something like the following:
```
xlab=function(slice,terminus){
              paste('time:',terminus,' total infected:',
                    sum(slice%v%'knowsRumor',na.rm=TRUE))
            }
```
[as seen here in the vignette](http://statnet.org/Workshops/ndtv_workshop.html).
