### ISSUE TITLE
Takedown warning from cran about missing tergm package

### ISSUE THREAD

**Issue by skyebend** [statnet/ndtv#52]
Dear maintainer,

Please see the problems shown on
[<https://cran.r-project.org/web/checks/check_results_ndtv.html>](https://cran.r-project.org/web/checks/check_results_ndtv.html).

Please correct before 2022-11-21 to safely retain your package on CRAN.

Packages in Suggests should be used conditionally: see 'Writing R Extensions'.
This needs to be corrected even if the missing package(s) become available.
It can be tested by checking with _R_CHECK_DEPENDS_ONLY_=true.

The CRAN Team

**Comment by krivit** [comment]
Someone who shall go unnamed changed a part of `ergm` API that broke `tergm`, so I am releasing them in rapid succession. This should fix itself shortly.

**Comment by skyebend** [comment]
corrections made, pushed to CRAN ... fingers crossed (skye, before closing this issue, don't forget to tag release)

**Comment by krivit** [comment]
Eh? I got `tergm` back on CRAN, so I didn't think any changes were needed.

**Comment by skyebend** [comment]
there was some examples code in the vignettes that I guess was not appropriately tolerant of missing Suggests packages (i.e. package shouldn't have broken w/o tergm anyway)

But seems all good now!

>Thanks, on its way to CRAN.
Best,
Uwe Ligges
